---
- name: Docker | install prerequisite packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
  - apt-transport-https
  - ca-certificates
  - software-properties-common

- name: Docker | add repository key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Docker | add repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes

- name: Docker | get latest point release
  shell: apt-cache madison docker-ce | grep {{ docker_version }} | head -1 | awk '{print $3}'
  register: docker_package_version

- name: Docker | install docker
  apt:
    name: docker-ce={{docker_package_version.stdout}}
    state: present

- name: Docker | pin the version of docker
  command: apt-mark hold docker-ce