---
- name: Facts | get the MAC address
  set_fact:
    mac_address: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress | regex_replace(':', '-') }}"

- name: Facts | get the mapped facts
  set_fact:
    hostname: "{{ mac_mapping[mac_address].hostname }}"
    interfaces: "{{ mac_mapping[mac_address].interfaces }}"