---
- name: Hostname | set the hostname
  hostname:
    name: "{{ hostname }}"
  tags: hostname

- name: Hostname | add myself to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ default_ip }}"
    line: "{{ default_ip }}\t{{ hostname }}"
    state: present
  notify:
    - restart system
  tags: hostname