---
- name: Hostname | get the MAC address
  set_fact:
    mac_address: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress | regex_replace(':', '-') }}"

- name: Hostname | get the MAC mappings
  set_fact:
    hostname: "{{ mac_mapping[mac_address].hostname }}"

- name: Hostname | set the hostname
  hostname:
    name: "{{ hostname }}"
  register: set_hostname
  tags: hostname

- name: Hostname | add myself to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1[ \t]+'
    line: "127.0.1.1\t{{ hostname }}"
    state: present
  tags: hostname