---
- name: Users | generate encrypted password
  shell: echo '{{ provisioning_password }}' | mkpasswd --method=sha-512 --stdin --salt='{{ inventory_hostname | hash('sha1') | truncate(16) }}'
  register: encrypted_password

- name: Users | add the Ansible user
  user:
    name: "{{ provisioning_username }}"
    shell: /bin/bash
    append: yes
    groups: sudo
    #password: "{{ provisioning_password | password_hash( 'sha512', 65534 | random(seed=inventory_hostname) | string ) }}"
    password: "{{encrypted_password.stdout_lines}}"

- name: Users | set authorized key
  authorized_key:
    user: "{{ provisioning_username }}"
    state: present
    key: "{{ provisioning_authorized_key }}"